name: bio-agent
channels:
  - bioconda
  - conda-forge
dependencies:
  - fastqc=0.12.1
  - trimmomatic=0.39
  - salmon=1.10.3
  - python=3.13.2
  - pip
  - pip:
      - 'smolagents[litellm]'
      - openai